"""Initial Tables

Revision ID: af0aa365c907
Revises: 
Create Date: 2025-09-12 11:03:04.661273

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'af0aa365c907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mintrecord',
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('image_cid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_hash', sqlmodel.sql.sqltypes.AutoString(length=66), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_hash')
    )
    op.create_index(op.f('ix_mintrecord_user_address'), 'mintrecord', ['user_address'], unique=False)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_mintrecord_user_address'), table_name='mintrecord')
    op.drop_table('mintrecord')
    # ### end Alembic commands ###
